// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnYrA6DUMF2FK5OBb7gaRWzKRCbWGQJ0',
    appId: '1:911137995684:web:aa639b461e4f929ec25f31',
    messagingSenderId: '911137995684',
    projectId: 'ettaba-99fa8',
    authDomain: 'ettaba-99fa8.firebaseapp.com',
    storageBucket: 'ettaba-99fa8.appspot.com',
    measurementId: 'G-H2J7C9EEKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8coqYUVrvh4tY9Gr19-CtK9FoTG8XUy0',
    appId: '1:911137995684:android:e8e934b7b3df3fd8c25f31',
    messagingSenderId: '911137995684',
    projectId: 'ettaba-99fa8',
    storageBucket: 'ettaba-99fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kTiNoA_pmccfQwfEFLKbcLaCOj9qRco',
    appId: '1:911137995684:ios:7712850337315304c25f31',
    messagingSenderId: '911137995684',
    projectId: 'ettaba-99fa8',
    storageBucket: 'ettaba-99fa8.appspot.com',
    iosBundleId: 'com.example.verifyEmailFirebaseAuthFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1kTiNoA_pmccfQwfEFLKbcLaCOj9qRco',
    appId: '1:911137995684:ios:c99ffd52fc34b664c25f31',
    messagingSenderId: '911137995684',
    projectId: 'ettaba-99fa8',
    storageBucket: 'ettaba-99fa8.appspot.com',
    iosBundleId: 'com.example.verifyEmailFirebaseAuthFlutter.RunnerTests',
  );
}
